name: CI/CD for Node.js Application

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build and push Docker image
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t akai7/azure-aks:$IMAGE_TAG .
        docker push akai7/azure-aks:$IMAGE_TAG
        echo "::set-output name=image::akai7/azure-aks:$IMAGE_TAG"
    - name: Clone manifest repo
      uses: actions/checkout@v2
      with:
        repository: mayureshmudrale/wohlig-yaml
        path: deployment-repo
        
                      

    
