name: CI/CD for Node.js Application

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build and push Docker image
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t akai7/azure-aks:$IMAGE_TAG .
        docker push akai7/azure-aks:$IMAGE_TAG
        echo "::set-output name=image::akai7/azure-aks:$IMAGE_TAG"
    - name: Update image tag
      run: |
        #sed -i "akai7/azure-aks:.*|akai7/azure-aks:${IMAGE_TAG}|"  yaml/deployment.yaml
        echo "image: akai7/azure-aks:$IMAGE_TAG" >> path/to/your/file.yaml
    - name: Commit and push updated YAML
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update image tag"
        git push
      env:
        token: ${{ secrets.TOKEN }} 
        
        
                      

    
